# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-09-12 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_auto_20190912_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gdrawn',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='glost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='gwon',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='college_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_no',
            field=models.CharField(max_length=10),
        ),
    ]
