# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-15 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_auto_20190912_1201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
        migrations.AddField(
            model_name='profile',
            name='bot_ext',
            field=models.CharField(default='cpp', max_length=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='bot_path',
            field=models.CharField(default='', max_length=50),
        ),
    ]
